### ISSUE TITLE
Can't open quarantine after upgrade from 1.9.0 to 1.10.1

### ISSUE THREAD

**Issue by lmfrazao** [modoboa/modoboa#1377]
# Impacted versions

* Modoboa: 1.10.1
* installer used: Yes ?
* Webserver: Nginx

OS: centos 7.4

# Steps to reproduce
Upgrade from 1.9.0

# Current behavior
Can't open quarantine - Internal Error
I have put Debug on, should open the debug log on modoboa ? can't see nothing on log files.

**Comment by fyfe** [comment]
In `settings.py` set `ADMINS` and it'll send error messages to that e-mail address:

```python
# A list of all the people who get code error notifications. When DEBUG=False
# and a view raises an exception, Django will email these people with the full
# exception information.
# See https://docs.djangoproject.com/en/dev/ref/settings/#admins
ADMINS = [('Administrator', 'admin@example.com')]

# The email address that error messages come from, such as those sent to ADMINS
SERVER_EMAIL = 'notifications@example.com'
```

**Comment by lmfrazao** [comment]
I have done it, but still no emails with debug information, is there any way I can force another error ?

**Comment by fyfe** [comment]
Try closing you're browser and reopening the quarantine page.

**Comment by lmfrazao** [comment]
already did it, cleared cache, and tryed other browsers

**Comment by fyfe** [comment]
Can you access the quarantine page now or does it still show the Internal Error message?

**Comment by lmfrazao** [comment]
Jan 29 17:47:00 xxxxxxx uwsgi: xxxxxxxx.xxx [pid: 1919|app: 2|req: 3/8] 192.168.33.8 () {54 vars in 1093                                                                          bytes} [Mon Jan 29 17:47:00 2018] GET /quarantine/listing/?sort_order=-date&reset_page=true&_=1517248020399 =>                                                                          generated 18132 bytes in 377 msecs (HTTP/1.1 500) 5 headers in 169 bytes (1 switches on core 0)

Best I can get when I access it .

**Comment by fyfe** [comment]
Is it only the quarantine page that isn't working?

**Comment by lmfrazao** [comment]
yes

**Comment by fyfe** [comment]
- can you try opening `/quarantine/listing/?sort_order=-date&reset_page=true` you should get a load of JSON.
- can you also post your settings.py
- which database server (and version) are you using?

**Comment by lmfrazao** [comment]
I'm using mariadb 5.5.56

Just noticed the database is in latin1, shall I convert it to utf-8 ?

It was working before this update, this "The string that could not be encoded/decoded was: o ve�culo." it's "o veículo"

error:

--------------------------

UnicodeDecodeError at /quarantine/listing/

'utf8' codec can't decode byte 0xed in position 12: invalid continuation byte

Request Method: 	GET
Request URL: 	https://xxx.xxx/quarantine/listing/?sort_order=-date&reset_page=true
Django Version: 	1.11.9
Exception Type: 	UnicodeDecodeError
Exception Value: 	

'utf8' codec can't decode byte 0xed in position 12: invalid continuation byte

Exception Location: 	/srv/modoboa/env/lib64/python2.7/encodings/utf_8.py in decode, line 16
Python Executable: 	/usr/sbin/uwsgi
Python Version: 	2.7.5
Python Path: 	

['.',
 '',
 '/srv/modoboa/env/lib64/python27.zip',
 '/srv/modoboa/env/lib64/python2.7',
 '/srv/modoboa/env/lib64/python2.7/plat-linux2',
 '/srv/modoboa/env/lib64/python2.7/lib-tk',
 '/srv/modoboa/env/lib64/python2.7/lib-old',
 '/srv/modoboa/env/lib64/python2.7/lib-dynload',
 '/usr/lib64/python2.7',
 '/usr/lib/python2.7',
 '/srv/modoboa/env/lib/python2.7/site-packages']

Server time: 	Mon, 29 Jan 2018 18:00:14 +0000
Unicode error hint

The string that could not be encoded/decoded was: o ve�culo

**Comment by lmfrazao** [comment]
Traceback:
Environment:


Request Method: GET
Request URL: https://xxxxxxxx.xx/quarantine/listing/?sort_order=-date&reset_page=true

Django Version: 1.11.9
Python Version: 2.7.5
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.sites',
 'django.contrib.staticfiles',
 'reversion',
 'ckeditor',
 'ckeditor_uploader',
 'rest_framework',
 'rest_framework.authtoken',
 'modoboa',
 'modoboa.core',
 'modoboa.lib',
 'modoboa.admin',
 'modoboa.transport',
 'modoboa.relaydomains',
 'modoboa.limits',
 'modoboa.parameters',
 'modoboa_amavis',
 'modoboa_pdfcredentials',
 'modoboa_postfix_autoreply',
 'modoboa_sievefilters',
 'modoboa_stats',
 'modoboa_contacts',
 'modoboa_dmarc',
 'modoboa_radicale',
 'webpack_loader')
Installed Middleware:
('x_forwarded_for.middleware.XForwardedForMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'modoboa.core.middleware.LocalConfigMiddleware',
 'modoboa.lib.middleware.AjaxLoginRedirect',
 'modoboa.lib.middleware.CommonExceptionCatcher',
 'modoboa.lib.middleware.RequestCatcherMiddleware')



Traceback:

File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/srv/modoboa/env/lib/python2.7/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/srv/modoboa/env/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/lib/python2.7/site-packages/django/utils/decorators.py" in inner
  185.                     return func(*args, **kwargs)

File "/srv/modoboa/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/views.py" in _listing
  105.     context = get_listing_pages(request, connector)

File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/views.py" in get_listing_pages
  66.         email_list += connector.fetch(page.id_start, page.id_stop)

File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/sql_connector.py" in fetch
  177.                 "subject": fix_utf8_encoding(qm["mail__subject"]),

File "/srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/utils.py" in fix_utf8_encoding
  61.     return value.encode("raw_unicode_escape").decode("utf-8")

File "/srv/modoboa/env/lib64/python2.7/encodings/utf_8.py" in decode
  16.     return codecs.utf_8_decode(input, errors, True)

Exception Type: UnicodeDecodeError at /quarantine/listing/
Exception Value: 'utf8' codec can't decode byte 0xed in position 12: invalid continuation byte

**Comment by fyfe** [comment]
Can you run the following SQL query on the amavis database:

```SQL
SELECT character_set_name FROM information_schema.`COLUMNS` 
WHERE table_schema = "schemaname"
  AND table_name = "msgs"
  AND column_name = "subject";
```

```shell
mysql -u [username] -p [database] 'SELECT character_set_name, collate_name FROM information_schema.`COLUMNS` WHERE table_schema = "schemaname" AND table_name = "msgs" AND column_name = "subject";'
```

**Comment by lmfrazao** [comment]
0 rows returned

**Comment by lmfrazao** [comment]
in module instance.settings on the error I got this:

AMAVIS_DEFAULT_DATABASE_ENCODING | u'LATIN1'

should be utf-8, since the database is on utf-8 ?

where can I change this ?

**Comment by fyfe** [comment]
Yes if you're database uses utf-8 encoding add `AMAVIS_DEFAULT_DATABASE_ENCODING = 'utf8'` to `settings.py`

Before you change it can you run the next command, there is a deployment check that should checks this is set to the correct value for your database:
```shell
python manage.py checks --deploy
```

If that doesn't work can you run the following SQL on the amavis database
```SQL
SHOW FULL COLUMNS FROM msgs;
```

**Comment by lmfrazao** [comment]
the result is: utf8mb4

**Comment by lmfrazao** [comment]
I get this:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib64/python2.7/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/lib64/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/lib64/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/lib64/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named transport

**Comment by fyfe** [comment]
Did you do all the [upgrade steps](https://modoboa.readthedocs.io/en/latest/upgrade.html#id2), you're probably missing `modoboa.transport` from `MODOBOA_APPS` in `settings.py`.

**Comment by lmfrazao** [comment]
I folowed the steps, yes.

I wasn't using modoboa user.

error:

Unknown command: 'checks'

**Comment by fyfe** [comment]
Sorry that should have been `check` (no s)

```shell
 python manage.py check --deploy
```

**Comment by lmfrazao** [comment]
?: (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.

this should be the error

**Comment by fyfe** [comment]
`AMAVIS_DEFAULT_DATABASE_ENCODING` should match the output from this SQL (change the database name if it's not amavis)
```SQL
SELECT DEFAULT_CHARACTER_SET_NAME
            FROM INFORMATION_SCHEMA.SCHEMATA
            WHERE SCHEMA_NAME = "amavis";
```

**Comment by lmfrazao** [comment]
![capture](https://user-images.githubusercontent.com/33859834/35528703-a6e400be-0526-11e8-9a67-baca70138a7b.PNG)
![capture1](https://user-images.githubusercontent.com/33859834/35528704-a702b4d2-0526-11e8-9648-7962cc752a81.PNG)

**Comment by lmfrazao** [comment]
on settings.py:
AMAVIS_DEFAULT_DATABASE_ENCODING = 'utf8'

**Comment by lmfrazao** [comment]
I have other errors btw, but I think it's shouldn't be related to this:

?: (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.
        HINT: Check your database character encoding and set/update AMAVIS_DEFAULT_DATABASE_ENCODING.
?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
?: (security.W012) SESSION_COOKIE_SECURE is not set to True. Using a secure-only session cookie makes it more difficult for network traffic sniffers to hijack user sessions.
?: (security.W016) You have 'django.middleware.csrf.CsrfViewMiddleware' in your MIDDLEWARE, but you have not set CSRF_COOKIE_SECURE to True. Using a secure-only CSRF cookie makes it more difficult for network traffic sniffers to steal the CSRF token.
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. The default is 'SAMEORIGIN', but unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'.

**Comment by fyfe** [comment]
`AMAVIS_DEFAULT_DATABASE_ENCODING = 'utf8'` is correct for you're database.

The other warnings are caused because we don't use `django.middleware.security.SecurityMiddleware` it's dealt with by nginx.

This looks like an issue with python not liking what's in the subject field, can you post the result for the following
```SQL
SELECT subject FROM msgs
```

**Comment by lmfrazao** [comment]
![capture](https://user-images.githubusercontent.com/33859834/35529685-abcc518c-0529-11e8-8d49-2dcb40fade7d.PNG)
just a sample

**Comment by fyfe** [comment]
I see the problem, unicode emoji, I hate them 😠 The `utf8` encoding in MySQL (and MariaDB) doesn't support the full range of unicode character (ie unicode emoji) that's why they added the `utf8mb4` encoding.

I'll need to go away and look a this again I might have to revert my original fix for this.
https://github.com/modoboa/modoboa-amavis/blob/master/modoboa_amavis/utils.py#L48

**Comment by fyfe** [comment]
Ok some quick research it's a python 2 issue, nothing to do with the database encoding.

**Comment by fyfe** [comment]
@lmfrazao in python could you run the following
```python
>>> import sys
>>> 'UCS4' if sys.maxunicode >= 0x10000 else 'UCS2'
```

**Comment by lmfrazao** [comment]
it returns 'UCS4'
same errors with  python manage.py check --deploy

**Comment by lmfrazao** [comment]
oww wait, the error with the check --deploy is gone

but what to do now ?

**Comment by lmfrazao** [comment]
@fyfe you figured out how to fix this ?

**Comment by lmfrazao** [comment]
I guess this should be a nub question.

I have done the modifications you have at https://github.com/modoboa/modoboa-amavis/pull/95/files

but how can I apply them now ?

**Comment by fyfe** [comment]
I've just had to fix 2 typos in utils.py 
```python
encoding = chardet.detect(value)
```
should be
```python
encoding = chardet.detect(bytes_value)
```

and

```python
except UnicodeDecodeError:
```
should be
```python
except (TypeError, UnicodeDecodeError):
```

After you've modified the files you need to restart modoboa for the changes to take effect.

**Comment by lmfrazao** [comment]
I guess I'll better wait for a commit:


Request Method: | GET
-- | --
https://modoboa.bild.pt/quarantine/listing/?sort_order=-date&reset_page=true
1.11.9
TypeError
not enough arguments for format string
/srv/modoboa/env/lib/python2.7/site-packages/modoboa_amavis/lib.py in cleanup_email_address, line 443
/usr/sbin/uwsgi
2.7.5
['.',  '',  '/srv/modoboa/env/lib64/python27.zip',  '/srv/modoboa/env/lib64/python2.7',  '/srv/modoboa/env/lib64/python2.7/plat-linux2',  '/srv/modoboa/env/lib64/python2.7/lib-tk',  '/srv/modoboa/env/lib64/python2.7/lib-old',  '/srv/modoboa/env/lib64/python2.7/lib-dynload',  '/usr/lib64/python2.7',  '/usr/lib/python2.7',  '/srv/modoboa/env/lib/python2.7/site-packages']
Tue, 30 Jan 2018 18:06:08 +0000

**Comment by lmfrazao** [comment]
ok, working now

I had on lib.py  adress = parseaddr(address) 

fixed now !

I owe you some beers 

thank you!

Btw is there any way to put some navigation on quarantine, listing 100 each for example ? would be good.

**Comment by WLR86** [comment]
It seems I'm having the very same issue ... How could I go about fixing this ? (Sorry guys, but can't figure out what to do from your posts)
Do I have to convert amavis DB to utf8mb4 ? 
Whatever I do suggested here in settings.py, I'm still getting this message when running "manage.py check --deploy":
```
?: (modoboa-amavis.W001) AMAVIS_DEFAULT_DATABASE_ENCODING does not match the character encoding used by the Amavis database.
        HINT: Check your database character encoding and set/update AMAVIS_DEFAULT_DATABASE_ENCODING.
```
Am I supposed to restart any process besides uwsgi when modifying settings.py  ?

Sorry if the answers to those questions looks obvious to you guys : /

**Comment by fresH229a** [comment]
Had the same issue and changed the things @fyfe wrote, working now on my site

**Comment by WLR86** [comment]
@fresH229a Yup I ended up doing this as well, and it seems to be working fine now - thanks for your input, this is much appreciated

**Comment by jing95** [comment]
I changed the things @fyfe wrote , but still getting those messages when running "manage.py check --deploy"
![image](https://user-images.githubusercontent.com/34827497/36774002-3eb5742c-1c97-11e8-9d30-a9a45b00482f.png)
maybe I miss something , so I'd like list the files I changed . And I wish someone could tell me what's missing...
1.settings.py 2.sql_connector.py 3.lib.py 4.utils.py
So, is there anything else I need to change?

Thank you in advance !

**Comment by tonioo** [comment]
The order is important: make sure the AMAVIS_DEFAULT_DATABASE_ENCODING is declared after the "from modoboa_amavis import settings..." line.

**Comment by jing95** [comment]
Hello @tonioo you mean this?

![image](https://user-images.githubusercontent.com/34827497/36777367-3041205a-1ca4-11e8-9aa0-c9acf364e762.png)

**Comment by tonioo** [comment]
@jing95 yes

**Comment by jing95** [comment]
So is it right?

**Comment by jing95** [comment]
That seems right.

**Comment by jing95** [comment]
@lmfrazao @WLR86 Sorry , I still don't understand how to do it , even if I have the very same problem , so I hope if you have time you can tell me where you're modified , and I can try to do it so .

**Comment by kryskool** [comment]
This issue move to https://github.com/modoboa/modoboa-amavis/issues/108
